//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPhone
    {
        public int Cust_Phone_ID { get; set; }
        public int Cust_ID { get; set; }
        public string Phone_Number { get; set; }
        public bool Active { get; set; }
    }
}
